#!/bin/bash
sudo yum -y install nfs-utils
sudo mkdir /mnt/efs
sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 10.0.230.10:/ /mnt/efs
sudo yum -y install  amazon-cloudwatch-agent
echo  "hello world" > /home/ec2-user/test