version: "3.8"

volumes:
  weather_app_db:

services:
  database:
    container_name: postgres
    hostname: postgres
    image: postgres
    volumes:
      - weather_app_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
    - postgresql

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4:snapshot
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
    - "5050:80"
    depends_on:
    - database
    networks:
    - postgresql

  flask_app:
    container_name: flask
    hostname: flask
    image: kolyavolkov/my_flask_app:latest
    restart: always
    environment:
      USER: "${USER}"
      API_KEY: "${API_KEY}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
    - "5000:5000"
    depends_on:
    - database
    - pgadmin
    networks:
    - postgresql

networks:
  postgresql:
    driver: bridge
