version: "3.8"

services:
  database:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
    - postgresql

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4:snapshot
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
    - "5050:80"
    depends_on:
    - database
    networks:
    - postgresql

  flask_app:
    container_name: flask
    hostname: flask
    build: .
    environment:
      USER: "${USER}"
      API_KEY: "${API_KEY}"
    ports:
    - "5000:5000"
    depends_on:
    - database
    networks:
    - postgresql
    
networks:
  postgresql:
    driver: bridge
