---
- name: Install dependencies for awscli
  apt:
    name: "python3-pip"
    state: latest
    update_cache: yes

- name: Install awscli with pip3
  pip:
    name: "awscli"
    executable: pip3

- name: Install boto with pip3
  pip:
    name: "boto3"
    executable: pip3

- name: Install Cloudwatch
  apt:
    deb: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
  notify: Cloudwatch is ready
